data_loader:
    users:
        path: src/data/datasets/u.user
        columns: ['userId', 'age', 'gender', 'job', 'zip_code']
    items:
        path: src/data/datasets/u.item
        columns: ['itemId', 'movie_title', 'release_date', 'video_release_date', 'IMDb_URL', 'unknown', 'Action', 'Adventure', 'Animation', 'Children', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
    ratings:
        path: src/data/datasets/u.data
        columns: ['userId', 'itemId', 'rating', 'timestamp']
#    items_attributes:
#        path: https://raw.githubusercontent.com/6oncvlo/Recommendation-System/main/Data/MovDetails.csv
cross_validation:
    iterator: 'KFold'
    metrics: ['mae', 'rmse', 'mse', 'fcp']
model:
    test_date: '19980402'
    algo_class: SVD