data_loader:
    users:
        path: src/data/datasets/u.user
        columns:
            - userId
            - age
            - gender
            - job
            - zip_code
    items:
        path: src/data/datasets/u.item
        columns:
            - itemId
            - movie_title
            - release_date
            - video_release_date
            - IMDb_URL
            - unknown
            - Action
            - Adventure
            - Animation
            - Children
            - Comedy
            - Crime
            - Documentary
            - Drama
            - Fantasy
            - Film-Noir
            - Horror
            - Musical
            - Mystery
            - Romance
            - Sci-Fi
            - Thriller
            - War
            - Western
    ratings:
        path: src/data/datasets/u.data
        columns:
            - userId
            - itemId
            - rating
            - timestamp
#    items_attributes:
#        path: https://raw.githubusercontent.com/6oncvlo/Recommendation-System/main/Data/MovDetails.csv
training :
    test_date : '19980402'
    model_selection :
        hold_out :
            validation_date : '19980312'
        KFold :
            n_splits : 5
            shuffle  : False
            random_state :
        RepeatedKFold :
            n_splits : 5
            n_repeats  : 10
            random_state : 0  
        ts_split :
            n_splits : 5
            max_train_size :
            test_size :
            gap : 0            
    params_algo :
        BaselineOnly :
            verbose      : [True]
        KNN :
            k            : [40]
            min_k        : [1]
            name         : ["msd"]
            user_based   : [True]
            min_support  : [5]
            shrinkage    : [null]
            verbose      : [True]
        MF_SVD :
            n_factors    : [200]
            n_epochs     : [100]
            biased       : [True]
            init_mean    : [0]
            init_std_dev : [0.1]
            lr_bu        : [0.005]
            lr_bi        : [0.005]
            lr_pu        : [0.005]
            lr_qi        : [0.005]
            reg_bu       : [0.02]
            reg_bi       : [0.02]
            reg_pu       : [0.02]
            reg_qi       : [0.02]
            random_state : [0]
            verbose      : [False]
        NMF :
            n_factors    : [15]
            n_epochs     : [50]
            biased       : [True]
            reg_pu       : [0.06]
            reg_qi       : [0.06]
            reg_bu       : [0.02]
            reg_bi       : [0.02]
            lr_bu        : [0.005]
            lr_bi        : [0.005]
            init_low     : [0]
            init_high    : [1]
            random_state : [0]
            verbose      : [False]
        CoClustering :
            n_cltr_u     : [3]
            n_cltr_i     : [3]
            n_epochs     : [20]
            random_state : [0]
            verbose      : [False]
            